name: build

env:
  XCODE_VERSION: 'Xcode_13.1'

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:

  build_verifier:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Switch to Xcode ${{ env.XCODE_VERSION }}
      run: sudo xcode-select --switch /Applications/${{ env.XCODE_VERSION }}.app
    
    # Compile "Release-Verifier-Prod" for iOS Simulator (no signing)
    - name: Compile Release-Verifier-Prod
      run: fastlane gym --scheme "Release-Verifier-Prod" --skip_package_ipa true --disable_package_automatic_updates true --destination "generic/platform=iOS Simulator"

  build_wallet:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Switch to Xcode ${{ env.XCODE_VERSION }}
      run: sudo xcode-select --switch /Applications/${{ env.XCODE_VERSION }}.app

    # Compile "Release-Wallet-Prod" for iOS Simulator (no signing)
    - name: Compile Release-Wallet-Prod
      run: fastlane gym --scheme "Release-Wallet-Prod" --skip_package_ipa true --disable_package_automatic_updates true --destination "generic/platform=iOS Simulator"
